/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poli.com.gui;


import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Duong
 */
public class DangKy extends javax.swing.JFrame {

    /**
     * Creates new form DangKy
     */
    public DangKy() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Đăng ký");
        jlbAnMK_DK.setVisible(false);
        jlbAnNLMK_DK.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTaoTK = new javax.swing.JPanel();
        jpnTieuDeTaoTK = new javax.swing.JPanel();
        jlbTieuDeTaoTK = new javax.swing.JLabel();
        jlbChaoMung = new javax.swing.JLabel();
        jlbMaNhanVien = new javax.swing.JLabel();
        jpnDuongThangMaNhanVien = new javax.swing.JPanel();
        txtMaNhanVien = new javax.swing.JTextField();
        jlbMatKhau = new javax.swing.JLabel();
        txtNhapLaiMK = new javax.swing.JPasswordField();
        jpnDuongThangMatKhau = new javax.swing.JPanel();
        jlbNhapLaiMK = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jpnDuongThangNhapLaiMK = new javax.swing.JPanel();
        btDangKy = new javax.swing.JButton();
        btQuayLai = new javax.swing.JButton();
        jlbHienMK_DK = new javax.swing.JLabel();
        jlbAnMK_DK = new javax.swing.JLabel();
        jlbHienNLMK_DK = new javax.swing.JLabel();
        jlbAnNLMK_DK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnTaoTK.setBackground(new java.awt.Color(255, 255, 255));
        jpnTaoTK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnTieuDeTaoTK.setBackground(new java.awt.Color(0, 153, 153));

        jlbTieuDeTaoTK.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        jlbTieuDeTaoTK.setForeground(new java.awt.Color(255, 255, 255));
        jlbTieuDeTaoTK.setText("TẠO TÀI KHOẢN MỚI");

        javax.swing.GroupLayout jpnTieuDeTaoTKLayout = new javax.swing.GroupLayout(jpnTieuDeTaoTK);
        jpnTieuDeTaoTK.setLayout(jpnTieuDeTaoTKLayout);
        jpnTieuDeTaoTKLayout.setHorizontalGroup(
            jpnTieuDeTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTieuDeTaoTKLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlbTieuDeTaoTK, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTieuDeTaoTKLayout.setVerticalGroup(
            jpnTieuDeTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTieuDeTaoTKLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlbTieuDeTaoTK)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpnTaoTK.add(jpnTieuDeTaoTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        jlbChaoMung.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 36)); // NOI18N
        jlbChaoMung.setForeground(new java.awt.Color(0, 153, 153));
        jlbChaoMung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/profile.png"))); // NOI18N
        jlbChaoMung.setText("       Tạo Tài Khoản");
        jpnTaoTK.add(jlbChaoMung, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 88, 510, -1));

        jlbMaNhanVien.setBackground(new java.awt.Color(0, 153, 153));
        jlbMaNhanVien.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jlbMaNhanVien.setForeground(new java.awt.Color(0, 153, 153));
        jlbMaNhanVien.setText("Mã nhân viên :");
        jpnTaoTK.add(jlbMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 205, -1, -1));

        jpnDuongThangMaNhanVien.setBackground(new java.awt.Color(0, 153, 153));
        jpnDuongThangMaNhanVien.setMaximumSize(new java.awt.Dimension(376, 376));
        jpnDuongThangMaNhanVien.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jpnDuongThangMaNhanVienLayout = new javax.swing.GroupLayout(jpnDuongThangMaNhanVien);
        jpnDuongThangMaNhanVien.setLayout(jpnDuongThangMaNhanVienLayout);
        jpnDuongThangMaNhanVienLayout.setHorizontalGroup(
            jpnDuongThangMaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnDuongThangMaNhanVienLayout.setVerticalGroup(
            jpnDuongThangMaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jpnTaoTK.add(jpnDuongThangMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 232, 510, 3));

        txtMaNhanVien.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        txtMaNhanVien.setBorder(null);
        jpnTaoTK.add(txtMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 205, 360, -1));

        jlbMatKhau.setBackground(new java.awt.Color(0, 153, 153));
        jlbMatKhau.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jlbMatKhau.setForeground(new java.awt.Color(0, 153, 153));
        jlbMatKhau.setText("Mật khẩu :");
        jpnTaoTK.add(jlbMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 264, -1, -1));

        txtNhapLaiMK.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        txtNhapLaiMK.setBorder(null);
        jpnTaoTK.add(txtNhapLaiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 330, 300, -1));

        jpnDuongThangMatKhau.setBackground(new java.awt.Color(0, 153, 153));
        jpnDuongThangMatKhau.setMaximumSize(new java.awt.Dimension(376, 376));
        jpnDuongThangMatKhau.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jpnDuongThangMatKhauLayout = new javax.swing.GroupLayout(jpnDuongThangMatKhau);
        jpnDuongThangMatKhau.setLayout(jpnDuongThangMatKhauLayout);
        jpnDuongThangMatKhauLayout.setHorizontalGroup(
            jpnDuongThangMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnDuongThangMatKhauLayout.setVerticalGroup(
            jpnDuongThangMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jpnTaoTK.add(jpnDuongThangMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 291, 510, 3));

        jlbNhapLaiMK.setBackground(new java.awt.Color(0, 153, 153));
        jlbNhapLaiMK.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jlbNhapLaiMK.setForeground(new java.awt.Color(0, 153, 153));
        jlbNhapLaiMK.setText("Nhập lại mật khẩu :");
        jpnTaoTK.add(jlbNhapLaiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 328, -1, -1));

        txtMatKhau.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        txtMatKhau.setBorder(null);
        jpnTaoTK.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 310, 30));

        jpnDuongThangNhapLaiMK.setBackground(new java.awt.Color(0, 153, 153));
        jpnDuongThangNhapLaiMK.setMaximumSize(new java.awt.Dimension(376, 376));
        jpnDuongThangNhapLaiMK.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jpnDuongThangNhapLaiMKLayout = new javax.swing.GroupLayout(jpnDuongThangNhapLaiMK);
        jpnDuongThangNhapLaiMK.setLayout(jpnDuongThangNhapLaiMKLayout);
        jpnDuongThangNhapLaiMKLayout.setHorizontalGroup(
            jpnDuongThangNhapLaiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnDuongThangNhapLaiMKLayout.setVerticalGroup(
            jpnDuongThangNhapLaiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jpnTaoTK.add(jpnDuongThangNhapLaiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 355, 510, 3));

        btDangKy.setBackground(new java.awt.Color(51, 51, 51));
        btDangKy.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        btDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btDangKy.setText("Đăng Ký");
        btDangKy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDangKyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDangKyMouseExited(evt);
            }
        });
        btDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangKyActionPerformed(evt);
            }
        });
        jpnTaoTK.add(btDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 510, 60));

        btQuayLai.setBackground(new java.awt.Color(51, 51, 51));
        btQuayLai.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        btQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        btQuayLai.setText("Quay Lại");
        btQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btQuayLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btQuayLaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btQuayLaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btQuayLaiMouseExited(evt);
            }
        });
        jpnTaoTK.add(btQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 510, 60));

        jlbHienMK_DK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/showMKDK.png"))); // NOI18N
        jlbHienMK_DK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbHienMK_DK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbHienMK_DKMousePressed(evt);
            }
        });
        jpnTaoTK.add(jlbHienMK_DK, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, -1, -1));

        jlbAnMK_DK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/hideMKDK.png"))); // NOI18N
        jlbAnMK_DK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbAnMK_DK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbAnMK_DKMousePressed(evt);
            }
        });
        jpnTaoTK.add(jlbAnMK_DK, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, -1, -1));

        jlbHienNLMK_DK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/showMKDK.png"))); // NOI18N
        jlbHienNLMK_DK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbHienNLMK_DK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbHienNLMK_DKMousePressed(evt);
            }
        });
        jpnTaoTK.add(jlbHienNLMK_DK, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, -1, -1));

        jlbAnNLMK_DK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/hideMKDK.png"))); // NOI18N
        jlbAnNLMK_DK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbAnNLMK_DK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbAnNLMK_DKMousePressed(evt);
            }
        });
        jpnTaoTK.add(jlbAnNLMK_DK, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTaoTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTaoTK, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQuayLaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuayLaiMouseEntered
        // TODO add your handling code here:
        btQuayLai.setBackground(Color.CYAN);
    }//GEN-LAST:event_btQuayLaiMouseEntered

    private void btQuayLaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuayLaiMouseExited
        // TODO add your handling code here:
        btQuayLai.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_btQuayLaiMouseExited

    private void jlbHienMK_DKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHienMK_DKMousePressed
        // TODO add your handling code here:
        jlbAnMK_DK.setVisible(true);
        jlbHienMK_DK.setVisible(false);
        txtMatKhau.setEchoChar((char)0);
    }//GEN-LAST:event_jlbHienMK_DKMousePressed

    private void jlbAnMK_DKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAnMK_DKMousePressed
        // TODO add your handling code here:
        jlbAnMK_DK.setVisible(false);
        jlbHienMK_DK.setVisible(true);
        txtMatKhau.setEchoChar('*');
    }//GEN-LAST:event_jlbAnMK_DKMousePressed

    private void jlbHienNLMK_DKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHienNLMK_DKMousePressed
        // TODO add your handling code here:
        jlbAnNLMK_DK.setVisible(true);
        jlbHienNLMK_DK.setVisible(false);
        txtNhapLaiMK.setEchoChar((char)0);
    }//GEN-LAST:event_jlbHienNLMK_DKMousePressed

    private void jlbAnNLMK_DKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAnNLMK_DKMousePressed
        // TODO add your handling code here:
        jlbAnNLMK_DK.setVisible(false);
        jlbHienNLMK_DK.setVisible(true);
        txtNhapLaiMK.setEchoChar('*');
    }//GEN-LAST:event_jlbAnNLMK_DKMousePressed

    private void btDangKyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangKyMouseEntered
        // TODO add your handling code here:
        btDangKy.setBackground(Color.CYAN);
    }//GEN-LAST:event_btDangKyMouseEntered

    private void btDangKyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangKyMouseExited
        // TODO add your handling code here:
        btDangKy.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_btDangKyMouseExited

    private void btQuayLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuayLaiMouseClicked
        // TODO add your handling code here:
        DangNhap dn = new DangNhap();
        this.setVisible(false);
        dn.setVisible(true);
    }//GEN-LAST:event_btQuayLaiMouseClicked

    private void btDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangKyActionPerformed
       boolean check  = kiemTraTT();
       if(check == false)
       {
           return;
       }
        boolean checkTT = poli.com.dao.taiKhoanDao.kiemTraKT(txtMaNhanVien.getText().toString());
        boolean kiemTraNV = poli.com.dao.nhanVienDao.check_maNV(txtMaNhanVien.getText().toString());
       if(kiemTraNV == true)
       {
            if(checkTT==true)
        {
             JOptionPane.showMessageDialog(this, "Mã nhân viên này đã đăng kí tài khoản rồi.", "Thông Báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {
            int quyen = poli.com.dao.nhanVienDao.check_Quyen_maNV(txtMaNhanVien.getText().toString()) ? 1 : 0;
             char[] passwordChars = txtMatKhau.getPassword();
            String password = new String(passwordChars);
            boolean checkDK = poli.com.dao.taiKhoanDao.themTK(txtMaNhanVien.getText().toString(), password, quyen);
            if(checkDK == true)
            {
                 JOptionPane.showMessageDialog(null, "Đăng kí thành công !!!", "Chúc mừng", JOptionPane.INFORMATION_MESSAGE);
                 clearData();
                return;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Đăng kí thất bại.", "Thông Báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Nhân viên này không tồn tại.", "Thông Báo", JOptionPane.WARNING_MESSAGE);
           return;
       }
    }//GEN-LAST:event_btDangKyActionPerformed
    void clearData()
    {
        txtMaNhanVien.setText("");
        txtMatKhau.setText("");
        txtNhapLaiMK.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKy().setVisible(true);
            }
        });
    }
    boolean kiemTraTT()
    {
         char[] passwordChars = txtMatKhau.getPassword();
    String password = new String(passwordChars);
    char[] passwordChars1 = txtNhapLaiMK.getPassword();
    String password1 = new String(passwordChars1);

    if(txtMaNhanVien.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên.", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        txtMaNhanVien.requestFocus();
        return false;
    }

    if(password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu.", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        txtMatKhau.requestFocus();
       return false;
    }

    if(password1.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập lại mật khẩu.", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        txtNhapLaiMK.requestFocus();
       return false;
    }

    if(!password.equals(password1)) {
        JOptionPane.showMessageDialog(this, "Mật khẩu không trùng khớp, vui lòng nhập lại.", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        txtMatKhau.requestFocus();
        return false;
    }
    return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangKy;
    private javax.swing.JButton btQuayLai;
    private javax.swing.JLabel jlbAnMK_DK;
    private javax.swing.JLabel jlbAnNLMK_DK;
    private javax.swing.JLabel jlbChaoMung;
    private javax.swing.JLabel jlbHienMK_DK;
    private javax.swing.JLabel jlbHienNLMK_DK;
    private javax.swing.JLabel jlbMaNhanVien;
    private javax.swing.JLabel jlbMatKhau;
    private javax.swing.JLabel jlbNhapLaiMK;
    private javax.swing.JLabel jlbTieuDeTaoTK;
    private javax.swing.JPanel jpnDuongThangMaNhanVien;
    private javax.swing.JPanel jpnDuongThangMatKhau;
    private javax.swing.JPanel jpnDuongThangNhapLaiMK;
    private javax.swing.JPanel jpnTaoTK;
    private javax.swing.JPanel jpnTieuDeTaoTK;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JPasswordField txtNhapLaiMK;
    // End of variables declaration//GEN-END:variables
}
