/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poli.com.gui;


import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.*;
import javax.swing.JPanel;
import poli.com.dao.SQLServerProvider;

/**
 *
 * @author Duong
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Đăng nhập");
        jlbAnMK.setVisible(false);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnAnh = new javax.swing.JPanel();
        jlbAnh = new javax.swing.JLabel();
        jpnThongTin = new javax.swing.JPanel();
        jlbTieuDe = new javax.swing.JLabel();
        jlbAnhTieuDe = new javax.swing.JLabel();
        jpbTK = new javax.swing.JPanel();
        jlbTK = new javax.swing.JLabel();
        jpnDuongThangTK = new javax.swing.JPanel();
        txtTK = new javax.swing.JTextField();
        jpnMK = new javax.swing.JPanel();
        jlbMK = new javax.swing.JLabel();
        jpnDuongThangMK = new javax.swing.JPanel();
        txtMK = new javax.swing.JPasswordField();
        jlbHienMK = new javax.swing.JLabel();
        jlbAnMK = new javax.swing.JLabel();
        btDangNhap = new javax.swing.JButton();
        btDangKy = new javax.swing.JButton();
        jlbQuenMK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/background(dn).jpg"))); // NOI18N

        javax.swing.GroupLayout jpnAnhLayout = new javax.swing.GroupLayout(jpnAnh);
        jpnAnh.setLayout(jpnAnhLayout);
        jpnAnhLayout.setHorizontalGroup(
            jpnAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnAnhLayout.setVerticalGroup(
            jpnAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbAnh)
        );

        jpnThongTin.setBackground(new java.awt.Color(51, 51, 51));
        jpnThongTin.setPreferredSize(new java.awt.Dimension(600, 600));

        jlbTieuDe.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        jlbTieuDe.setForeground(new java.awt.Color(255, 255, 255));
        jlbTieuDe.setText("Welcome");

        jlbAnhTieuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/profile.png"))); // NOI18N

        jpbTK.setBackground(new java.awt.Color(51, 51, 51));

        jlbTK.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jlbTK.setForeground(new java.awt.Color(255, 255, 255));
        jlbTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/account.png"))); // NOI18N
        jlbTK.setText("Tài khoản :");

        jpnDuongThangTK.setBackground(new java.awt.Color(255, 255, 255));
        jpnDuongThangTK.setMaximumSize(new java.awt.Dimension(376, 376));
        jpnDuongThangTK.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jpnDuongThangTKLayout = new javax.swing.GroupLayout(jpnDuongThangTK);
        jpnDuongThangTK.setLayout(jpnDuongThangTKLayout);
        jpnDuongThangTKLayout.setHorizontalGroup(
            jpnDuongThangTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnDuongThangTKLayout.setVerticalGroup(
            jpnDuongThangTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        txtTK.setBackground(new java.awt.Color(51, 51, 51));
        txtTK.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        txtTK.setForeground(new java.awt.Color(255, 255, 255));
        txtTK.setBorder(null);

        javax.swing.GroupLayout jpbTKLayout = new javax.swing.GroupLayout(jpbTK);
        jpbTK.setLayout(jpbTKLayout);
        jpbTKLayout.setHorizontalGroup(
            jpbTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbTKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpbTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnDuongThangTK, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(jpbTKLayout.createSequentialGroup()
                        .addComponent(jlbTK, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpbTKLayout.setVerticalGroup(
            jpbTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbTKLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jpbTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTK)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDuongThangTK, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnMK.setBackground(new java.awt.Color(51, 51, 51));
        jpnMK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbMK.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jlbMK.setForeground(new java.awt.Color(255, 255, 255));
        jlbMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/password.png"))); // NOI18N
        jlbMK.setText(" Mật khẩu :");
        jpnMK.add(jlbMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 159, -1));

        jpnDuongThangMK.setBackground(new java.awt.Color(255, 255, 255));
        jpnDuongThangMK.setMaximumSize(new java.awt.Dimension(376, 376));
        jpnDuongThangMK.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jpnDuongThangMKLayout = new javax.swing.GroupLayout(jpnDuongThangMK);
        jpnDuongThangMK.setLayout(jpnDuongThangMKLayout);
        jpnDuongThangMKLayout.setHorizontalGroup(
            jpnDuongThangMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnDuongThangMKLayout.setVerticalGroup(
            jpnDuongThangMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jpnMK.add(jpnDuongThangMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 527, 3));

        txtMK.setBackground(new java.awt.Color(51, 51, 51));
        txtMK.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        txtMK.setForeground(new java.awt.Color(255, 255, 255));
        txtMK.setBorder(null);
        jpnMK.add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 14, 300, -1));

        jlbHienMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/showMKDN.png"))); // NOI18N
        jlbHienMK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbHienMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbHienMKMousePressed(evt);
            }
        });
        jpnMK.add(jlbHienMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jlbAnMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/hideMKDN.png"))); // NOI18N
        jlbAnMK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbAnMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbAnMKMousePressed(evt);
            }
        });
        jpnMK.add(jlbAnMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        btDangNhap.setBackground(new java.awt.Color(51, 51, 51));
        btDangNhap.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        btDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btDangNhap.setText("Đăng nhập");
        btDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDangNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDangNhapMouseExited(evt);
            }
        });
        btDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangNhapActionPerformed(evt);
            }
        });

        btDangKy.setBackground(new java.awt.Color(51, 51, 51));
        btDangKy.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        btDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btDangKy.setText("Đăng ký");
        btDangKy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDangKyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDangKyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDangKyMouseExited(evt);
            }
        });

        jlbQuenMK.setBackground(new java.awt.Color(51, 51, 51));
        jlbQuenMK.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jlbQuenMK.setForeground(new java.awt.Color(255, 255, 255));
        jlbQuenMK.setText("Quên mật khẩu ?");
        jlbQuenMK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbQuenMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbQuenMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbQuenMKMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnThongTinLayout = new javax.swing.GroupLayout(jpnThongTin);
        jpnThongTin.setLayout(jpnThongTinLayout);
        jpnThongTinLayout.setHorizontalGroup(
            jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongTinLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbQuenMK)
                .addGap(48, 48, 48))
            .addGroup(jpnThongTinLayout.createSequentialGroup()
                .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jlbAnhTieuDe)
                            .addComponent(jlbTieuDe)))
                    .addGroup(jpnThongTinLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jpbTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDangNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDangKy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnMK, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnThongTinLayout.setVerticalGroup(
            jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jlbAnhTieuDe)
                .addGap(18, 18, 18)
                .addComponent(jlbTieuDe)
                .addGap(39, 39, 39)
                .addComponent(jpbTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jpnMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbQuenMK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangNhapMouseEntered
        // TODO add your handling code here:
        btDangNhap.setBackground(Color.CYAN);
    }//GEN-LAST:event_btDangNhapMouseEntered

    private void btDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangNhapMouseExited
        // TODO add your handling code here:
        btDangNhap.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_btDangNhapMouseExited

    private void btDangKyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangKyMouseEntered
        // TODO add your handling code here:
        btDangKy.setBackground(Color.CYAN);
    }//GEN-LAST:event_btDangKyMouseEntered

    private void btDangKyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangKyMouseExited
        // TODO add your handling code here:
        btDangKy.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_btDangKyMouseExited

    private void jlbQuenMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuenMKMouseEntered
        // TODO add your handling code here:
        jlbQuenMK.setForeground(Color.red);
    }//GEN-LAST:event_jlbQuenMKMouseEntered

    private void jlbQuenMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuenMKMouseExited
        // TODO add your handling code here:
        jlbQuenMK.setForeground(Color.WHITE);
    }//GEN-LAST:event_jlbQuenMKMouseExited
    boolean check_In_Put()
    {
        if(txtTK.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin(Tài khoản).", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
             txtTK.requestFocus();
            return false;
        }
        if(txtMK.getPassword().length==0)
        {
             JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống!!!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
             txtMK.requestFocus();
            return false;
        }
        return true;
    }
    private void btDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangNhapActionPerformed
        // TODO add your handling code here:
        if(check_In_Put()==false)
        {
            return;
        }
        String username = txtTK.getText().trim();
       
        char[] passwordChars = txtMK.getPassword();
        String password = new String(passwordChars);

        if(poli.com.dao.taiKhoanDao.checkDangNhap(username, password)==0) {
            poli.com.dao.SQLServerProvider.check_nhan_vien = username;
            MainJFrame mainFrame = new MainJFrame();
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
            mainFrame.setVisible(true); 
            this.dispose();
        }
        else if(poli.com.dao.taiKhoanDao.checkDangNhap(username, password)==1)
        {
            poli.com.dao.SQLServerProvider.check_nhan_vien = username;
            GiaoDienNV nv = new GiaoDienNV();
             JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
            nv.setVisible(true);
            this.dispose();
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Sai thông tin đăng nhâp ( tài khoản hoặc mật khẩu )", "Thông Báo", JOptionPane.WARNING_MESSAGE);
           return ;
        }
    }//GEN-LAST:event_btDangNhapActionPerformed

    private void jlbHienMKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHienMKMousePressed
        // TODO add your handling code here:
        jlbAnMK.setVisible(true);
        jlbHienMK.setVisible(false);
        txtMK.setEchoChar((char)0);
    }//GEN-LAST:event_jlbHienMKMousePressed

    private void jlbAnMKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAnMKMousePressed
        // TODO add your handling code here:
        jlbAnMK.setVisible(false);
        jlbHienMK.setVisible(true);
        txtMK.setEchoChar('*');
    }//GEN-LAST:event_jlbAnMKMousePressed

    private void btDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDangKyMouseClicked
        // TODO add your handling code here:
        DangKy dk = new DangKy();
        this.setVisible(false);
        dk.setVisible(true);
    }//GEN-LAST:event_btDangKyMouseClicked

    private void jlbQuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuenMKMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Vui lòng liên hệ với admin hoặc quản lí để được cấp lại mật khẩu.", "Thông Báo", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jlbQuenMKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangKy;
    private javax.swing.JButton btDangNhap;
    private javax.swing.JLabel jlbAnMK;
    private javax.swing.JLabel jlbAnh;
    private javax.swing.JLabel jlbAnhTieuDe;
    private javax.swing.JLabel jlbHienMK;
    private javax.swing.JLabel jlbMK;
    private javax.swing.JLabel jlbQuenMK;
    private javax.swing.JLabel jlbTK;
    private javax.swing.JLabel jlbTieuDe;
    private javax.swing.JPanel jpbTK;
    private javax.swing.JPanel jpnAnh;
    private javax.swing.JPanel jpnDuongThangMK;
    private javax.swing.JPanel jpnDuongThangTK;
    private javax.swing.JPanel jpnMK;
    private javax.swing.JPanel jpnThongTin;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
