/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poli.com.gui;


import com.toedter.calendar.JDateChooser;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Duong
 */
public class ThemMuonSach extends javax.swing.JFrame {
    private MainJFrame mainFrame;
    private GiaoDienNV dienNV;
    private int check = 0;

    /**
     * Creates new form ThemMuonSach
     */
    public ThemMuonSach(MainJFrame mainFrame) {
   
        check = 1;
        initComponents();
        this.mainFrame = mainFrame;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jdcNgayMuon_ThemPM.getDateEditor().setEnabled(false);
        load_the(jcbST_ThemPM, jdcNgayMuon_ThemPM);
        txtTenDG.setEditable(false);
        setTitle("Thêm phiếu mượn");
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                setVisible(false);
                mainFrame.loadTT_PM();
            }
            
});
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
        public ThemMuonSach(GiaoDienNV dienNV) {
        check = 2;
        initComponents();
        this.dienNV = dienNV;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        load_the(jcbST_ThemPM, jdcNgayMuon_ThemPM);
        txtTenDG.setEditable(false);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                setVisible(false);
                dienNV.loadTT_PM();
            }
            
});
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnThemMS = new javax.swing.JPanel();
        jpnTaoTTPM = new javax.swing.JPanel();
        jlbTieuDeTaoTTPM = new javax.swing.JLabel();
        jpnTTPM = new javax.swing.JPanel();
        jlbST_ThemPM = new javax.swing.JLabel();
        jcbST_ThemPM = new javax.swing.JComboBox<>();
        jpnST_ThemPM = new javax.swing.JPanel();
        jlbTenDG = new javax.swing.JLabel();
        txtTenDG = new javax.swing.JTextField();
        jpnDuongThangTenDG = new javax.swing.JPanel();
        jlbNgayMuon_ThemPM = new javax.swing.JLabel();
        jpnDuongThangNgayMuon1 = new javax.swing.JPanel();
        jdcNgayMuon_ThemPM = new com.toedter.calendar.JDateChooser();
        jlbNgayHenTra_ThemPM = new javax.swing.JLabel();
        jdcNgayHenTra_ThemPM = new com.toedter.calendar.JDateChooser();
        jpnDuongThangNgayHenTra_ThemPM = new javax.swing.JPanel();
        btTao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnThemMS.setPreferredSize(new java.awt.Dimension(1000, 600));

        jpnTaoTTPM.setBackground(new java.awt.Color(0, 153, 153));

        jlbTieuDeTaoTTPM.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        jlbTieuDeTaoTTPM.setForeground(new java.awt.Color(255, 255, 255));
        jlbTieuDeTaoTTPM.setText("TẠO THÔNG TIN PHIẾU MƯỢN");

        javax.swing.GroupLayout jpnTaoTTPMLayout = new javax.swing.GroupLayout(jpnTaoTTPM);
        jpnTaoTTPM.setLayout(jpnTaoTTPMLayout);
        jpnTaoTTPMLayout.setHorizontalGroup(
            jpnTaoTTPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTaoTTPMLayout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jlbTieuDeTaoTTPM, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTaoTTPMLayout.setVerticalGroup(
            jpnTaoTTPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTaoTTPMLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlbTieuDeTaoTTPM)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpnTTPM.setBackground(new java.awt.Color(255, 255, 255));
        jpnTTPM.setPreferredSize(new java.awt.Dimension(1000, 530));

        jlbST_ThemPM.setBackground(new java.awt.Color(0, 153, 153));
        jlbST_ThemPM.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jlbST_ThemPM.setForeground(new java.awt.Color(0, 153, 153));
        jlbST_ThemPM.setText("Số thẻ");

        jcbST_ThemPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbST_ThemPM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbST_ThemPMItemStateChanged(evt);
            }
        });

        jpnST_ThemPM.setBackground(new java.awt.Color(0, 153, 153));
        jpnST_ThemPM.setMaximumSize(new java.awt.Dimension(376, 376));
        jpnST_ThemPM.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jpnST_ThemPMLayout = new javax.swing.GroupLayout(jpnST_ThemPM);
        jpnST_ThemPM.setLayout(jpnST_ThemPMLayout);
        jpnST_ThemPMLayout.setHorizontalGroup(
            jpnST_ThemPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnST_ThemPMLayout.setVerticalGroup(
            jpnST_ThemPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jlbTenDG.setBackground(new java.awt.Color(0, 153, 153));
        jlbTenDG.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jlbTenDG.setForeground(new java.awt.Color(0, 153, 153));
        jlbTenDG.setText("Tên độc giả");

        txtTenDG.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        txtTenDG.setBorder(null);

        jpnDuongThangTenDG.setBackground(new java.awt.Color(0, 153, 153));
        jpnDuongThangTenDG.setMaximumSize(new java.awt.Dimension(376, 376));
        jpnDuongThangTenDG.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jpnDuongThangTenDGLayout = new javax.swing.GroupLayout(jpnDuongThangTenDG);
        jpnDuongThangTenDG.setLayout(jpnDuongThangTenDGLayout);
        jpnDuongThangTenDGLayout.setHorizontalGroup(
            jpnDuongThangTenDGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnDuongThangTenDGLayout.setVerticalGroup(
            jpnDuongThangTenDGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jlbNgayMuon_ThemPM.setBackground(new java.awt.Color(0, 153, 153));
        jlbNgayMuon_ThemPM.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jlbNgayMuon_ThemPM.setForeground(new java.awt.Color(0, 153, 153));
        jlbNgayMuon_ThemPM.setText("Ngày mượn");

        jpnDuongThangNgayMuon1.setBackground(new java.awt.Color(0, 153, 153));
        jpnDuongThangNgayMuon1.setMaximumSize(new java.awt.Dimension(376, 376));
        jpnDuongThangNgayMuon1.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jpnDuongThangNgayMuon1Layout = new javax.swing.GroupLayout(jpnDuongThangNgayMuon1);
        jpnDuongThangNgayMuon1.setLayout(jpnDuongThangNgayMuon1Layout);
        jpnDuongThangNgayMuon1Layout.setHorizontalGroup(
            jpnDuongThangNgayMuon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnDuongThangNgayMuon1Layout.setVerticalGroup(
            jpnDuongThangNgayMuon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jdcNgayMuon_ThemPM.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayMuon_ThemPM.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N

        jlbNgayHenTra_ThemPM.setBackground(new java.awt.Color(0, 153, 153));
        jlbNgayHenTra_ThemPM.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jlbNgayHenTra_ThemPM.setForeground(new java.awt.Color(0, 153, 153));
        jlbNgayHenTra_ThemPM.setText("Ngày hẹn trả");

        jdcNgayHenTra_ThemPM.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayHenTra_ThemPM.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N

        jpnDuongThangNgayHenTra_ThemPM.setBackground(new java.awt.Color(0, 153, 153));
        jpnDuongThangNgayHenTra_ThemPM.setMaximumSize(new java.awt.Dimension(376, 376));
        jpnDuongThangNgayHenTra_ThemPM.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jpnDuongThangNgayHenTra_ThemPMLayout = new javax.swing.GroupLayout(jpnDuongThangNgayHenTra_ThemPM);
        jpnDuongThangNgayHenTra_ThemPM.setLayout(jpnDuongThangNgayHenTra_ThemPMLayout);
        jpnDuongThangNgayHenTra_ThemPMLayout.setHorizontalGroup(
            jpnDuongThangNgayHenTra_ThemPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnDuongThangNgayHenTra_ThemPMLayout.setVerticalGroup(
            jpnDuongThangNgayHenTra_ThemPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btTao.setBackground(new java.awt.Color(0, 153, 153));
        btTao.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        btTao.setForeground(new java.awt.Color(255, 255, 255));
        btTao.setText("Tạo");
        btTao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnTTPMLayout = new javax.swing.GroupLayout(jpnTTPM);
        jpnTTPM.setLayout(jpnTTPMLayout);
        jpnTTPMLayout.setHorizontalGroup(
            jpnTTPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTTPMLayout.createSequentialGroup()
                .addGroup(jpnTTPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnTTPMLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(jpnTTPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpnTTPMLayout.createSequentialGroup()
                                .addComponent(jlbNgayHenTra_ThemPM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jdcNgayHenTra_ThemPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jpnST_ThemPM, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addGroup(jpnTTPMLayout.createSequentialGroup()
                                .addComponent(jlbST_ThemPM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbST_ThemPM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jpnDuongThangTenDG, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addGroup(jpnTTPMLayout.createSequentialGroup()
                                .addComponent(jlbNgayMuon_ThemPM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jdcNgayMuon_ThemPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpnTTPMLayout.createSequentialGroup()
                                .addComponent(jlbTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpnDuongThangNgayMuon1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addComponent(jpnDuongThangNgayHenTra_ThemPM, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)))
                    .addGroup(jpnTTPMLayout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(btTao, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 244, Short.MAX_VALUE))
        );
        jpnTTPMLayout.setVerticalGroup(
            jpnTTPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTTPMLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jpnTTPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbST_ThemPM)
                    .addComponent(jcbST_ThemPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnST_ThemPM, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jpnTTPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTenDG)
                    .addComponent(txtTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDuongThangTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jpnTTPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbNgayMuon_ThemPM)
                    .addComponent(jdcNgayMuon_ThemPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDuongThangNgayMuon1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jpnTTPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbNgayHenTra_ThemPM)
                    .addComponent(jdcNgayHenTra_ThemPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDuongThangNgayHenTra_ThemPM, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btTao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jpnThemMSLayout = new javax.swing.GroupLayout(jpnThemMS);
        jpnThemMS.setLayout(jpnThemMSLayout);
        jpnThemMSLayout.setHorizontalGroup(
            jpnThemMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTaoTTPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnTTPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnThemMSLayout.setVerticalGroup(
            jpnThemMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThemMSLayout.createSequentialGroup()
                .addComponent(jpnTaoTTPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTTPM, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnThemMS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnThemMS, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbST_ThemPMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbST_ThemPMItemStateChanged
        txtTenDG.setText(poli.com.dao.docGiaDao.layTen_AVT((String)jcbST_ThemPM.getSelectedItem()));
        
        
    }//GEN-LAST:event_jcbST_ThemPMItemStateChanged

    private void btTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaoActionPerformed
           if(check==1)
           {
                  if(jcbST_ThemPM.getSelectedIndex()==-1)
        {
             JOptionPane.showMessageDialog(null, "Vui lòng chọn mã thẻ!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
             return; 
        }
         if (jdcNgayMuon_ThemPM.getDate() == null) {
             
            JOptionPane.showMessageDialog(null, "Ngày mượn không được để trống !!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
         if(txtTenDG.getText().isEmpty())
         {
              JOptionPane.showMessageDialog(null, "Thẻ này chưa đăng kí độc giả!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
         }

        // Kiểm tra null cho henTra
        if (jdcNgayHenTra_ThemPM.getDate() == null) {
           
            JOptionPane.showMessageDialog(null, "Ngày hẹn trả không được để trống !!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
             java.sql.Date ngayMuon = new java.sql.Date(jdcNgayMuon_ThemPM.getDate().getTime());
            java.sql.Date ngayTra = new java.sql.Date(jdcNgayHenTra_ThemPM.getDate().getTime());
     
        
         
        boolean checkKQ = poli.com.dao.muonTraDao.themPhieuMuon((String)jcbST_ThemPM.getSelectedItem(), poli.com.dao.SQLServerProvider.check_nhan_vien, ngayMuon, ngayTra);
        if(checkKQ==true)
        {
            mainFrame.loadTT_PM();
             this.setVisible(false);
        }
        else
            
        {
             return;
        }
           }
           else if(check == 2)
           {
                  if(jcbST_ThemPM.getSelectedIndex()==-1)
        {
             JOptionPane.showMessageDialog(null, "Vui lòng chọn mã thẻ!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
             return; 
        }
         if (jdcNgayMuon_ThemPM.getDate() == null) {
             
            JOptionPane.showMessageDialog(null, "Ngày mượn không được để trống !!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra null cho henTra
        if (jdcNgayHenTra_ThemPM.getDate() == null) {
           
            JOptionPane.showMessageDialog(null, "Ngày hẹn trả không được để trống !!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
             java.sql.Date ngayMuon = new java.sql.Date(jdcNgayMuon_ThemPM.getDate().getTime());
            java.sql.Date ngayTra = new java.sql.Date(jdcNgayHenTra_ThemPM.getDate().getTime());
     
        
         
        boolean checkKQ = poli.com.dao.muonTraDao.themPhieuMuon((String)jcbST_ThemPM.getSelectedItem(), poli.com.dao.SQLServerProvider.check_nhan_vien, ngayMuon, ngayTra);
        if(checkKQ==true)
        {
            dienNV.loadTT_PM();
             this.setVisible(false);
        }
        else
            
        {
             return;
        }
           }
           else
           {
               return;
           }
    }//GEN-LAST:event_btTaoActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(ThemMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(ThemMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(ThemMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(ThemMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            MainJFrame mainFrame = new MainJFrame(); // Khởi tạo MainJFrame trước
            new ThemMuonSach(mainFrame).setVisible(true); // Truyền MainJFrame vào constructor của ThemMuonSach
        }
    });
}
     void load_the(JComboBox<String> x,JDateChooser date)
    {
        x.removeAllItems();
      
        String []ds = poli.com.dao.docGiaDao.select_soThe();
        for(String s : ds)
        {
            x.addItem(s);
            
        }      
        x.setSelectedIndex(-1);  
        java.util.Date currentDate = new java.util.Date();
        date.setDate(currentDate);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTao;
    private javax.swing.JComboBox<String> jcbST_ThemPM;
    private com.toedter.calendar.JDateChooser jdcNgayHenTra_ThemPM;
    private com.toedter.calendar.JDateChooser jdcNgayMuon_ThemPM;
    private javax.swing.JLabel jlbNgayHenTra_ThemPM;
    private javax.swing.JLabel jlbNgayMuon_ThemPM;
    private javax.swing.JLabel jlbST_ThemPM;
    private javax.swing.JLabel jlbTenDG;
    private javax.swing.JLabel jlbTieuDeTaoTTPM;
    private javax.swing.JPanel jpnDuongThangNgayHenTra_ThemPM;
    private javax.swing.JPanel jpnDuongThangNgayMuon1;
    private javax.swing.JPanel jpnDuongThangTenDG;
    private javax.swing.JPanel jpnST_ThemPM;
    private javax.swing.JPanel jpnTTPM;
    private javax.swing.JPanel jpnTaoTTPM;
    private javax.swing.JPanel jpnThemMS;
    private javax.swing.JTextField txtTenDG;
    // End of variables declaration//GEN-END:variables
}
